-d /run/host/var/home/felix/Documents/Projects/fpga-start/Sipeed-Tang-Nano-9K/03_led_matrix/impl/gwsynthesis/03_led_matrix.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst /run/host/var/home/felix/Documents/Projects/fpga-start/Sipeed-Tang-Nano-9K/03_led_matrix/src/03_led_matrix.cst
-cfg /run/host/var/home/felix/Documents/Projects/fpga-start/Sipeed-Tang-Nano-9K/03_led_matrix/impl/pnr/device.cfg
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
